// warmgun/src/components/@ui-elements/FormInput.svelte
<script lang="ts">
	export let type: string = 'text';
	export let name: string;
	export let placeholder: string = '';
	export let labelText: string = '';
	export let helperText: string = '';
</script>

<label class="space-y-2" for={name}>
	{#if labelText}
		<span class="text-sm opacity-75">{labelText}</span>
	{/if}

	<div class="input-group input-group-divider grid-cols-[auto_1fr_auto]">
		{#if $$slots.icon}
			<div class="input-group-shim">
				<slot name="icon" />
			</div>
		{/if}

		<input {type} {name} id={name} {placeholder} required />
	</div>

	{#if helperText}
		<p class="unstyled text-sm opacity-75">{helperText}</p>
	{/if}
</label>

// my-app/src/components/ui-blocks/FormInput.tsx
import React from "react"
import { LucideIcon, LucideProps } from "lucide-react"

import { Input } from "../ui/input"

export interface FormInputProps
  extends React.InputHTMLAttributes<HTMLInputElement> {
  labelText?: string
  helperText?: string
}

const FormInput = React.forwardRef<HTMLInputElement, FormInputProps>(
  (
    { className, type, placeholder, name, labelText, helperText, ...props },
    ref
  ) => {
    return (
      <label className="space-y-2" htmlFor={name}>
        {labelText && <span className="text-sm opacity-75">{labelText}</span>}

        <Input
          type={type}
          placeholder={placeholder}
          className={className}
          ref={ref}
          name={name}
          id={name}
          {...props}
        />

        {helperText && <p className="text-sm opacity-75">{helperText}</p>}
      </label>
    )
  }
)
FormInput.displayName = "FormInput"

export { FormInput }
