// src/app/[blog]/_components/blog-header.tsx
import Link from "next/link"

import { getServerSession } from "@/lib/auth"
import { fetchOneUser } from "@/lib/services/user/fetch"
import { buttonVariants } from "@/components/@ui/button"
import { Container } from "@/components/@ui/container"
import { TextWithIcon } from "@/components/@ui/text-with-icon"
import { UserMenu } from "@/components/app-shell/default-header/user-menu"

type BlogHeaderProps = {
  blogerUsername: string
}

export const BlogHeader = async ({ blogerUsername }: BlogHeaderProps) => {
  const session = await getServerSession()
  const bloger = await fetchOneUser(blogerUsername)

  return (
    <header className="sticky top-0 z-30 w-full border-b bg-background">
      <Container
        variant="wide"
        center
        className="flex h-16 items-center justify-between"
      >
        <div>
          <TextWithIcon
            icon={(Icons) => (
              <Link
                className={buttonVariants({
                  variant: "base",
                  onlyIcon: true,
                  size: "sm",
                })}
                href="/"
              >
                <Icons.Logo className="h-4 w-4" />
              </Link>
            )}
            text={(Text) => (
              <Link href={`/@${bloger?.username}`}>
                <Text size="lg" weight={500}>
                  {bloger?.profile?.blogName}
                </Text>
              </Link>
            )}
            gap={3.5}
          />
        </div>
        <div>
          {session?.user ? (
            <UserMenu
              name={session.user.username}
              image={session.user.profile?.avatar}
            />
          ) : (
            <Link className={buttonVariants()} href="/login">
              로그인
            </Link>
          )}
        </div>
      </Container>
    </header>
  )
}

// real/src/routes/(me)/[page=blog]/_BlogHeader/BlogHeader.svelte
<script lang="ts">
	import SearchIcon from '$components/@icons/SearchIcon.svelte';
	import UserPopup from '$components/@ui/Popup/UserPopup.svelte';
	import LogoIcon from '$components/@icons/LogoIcon.svelte';
	import { siteConfig } from '$lib/configs/site';
</script>

<header class="bg-background sticky top-0 z-40 w-full border-b border-b-surface-600">
	<div class="container h-16 flex items-center justify-between">
		<div class="flex items-center gap-2">
			<a href="/" class="flex items-center gap-2">
				<LogoIcon class="h-6 w-6" />
				<h2 class="hidden font-bold md:block">{siteConfig.name}</h2>
			</a>
		</div>

		<div class="flex items-center gap-2">
			<a href="/search" class="btn-icon">
				<SearchIcon class="w-6 h-6" />
			</a>
			<UserPopup />
		</div>
	</div>
</header>
