// src/components/@custom/AutosizedTextarea.svelte
<script lang="ts">
	import autosize from 'autosize';

	type TextareaSize = 'sm' | 'md' | 'lg';

	export let name: string;
	export let value: string;
	export let placeholder: string = '';
	export let size: TextareaSize = 'md';

	let textarea: Element;

	$: autosize(textarea);
	$: textareaSize = size === 'md' ? 'h-8 text-xl' : size === 'lg' ? 'h-14 text-3xl' : 'h-6 text-lg';
</script>

<textarea
	class={`unstyled w-full resize-none border-0 bg-transparent font-bold focus:!outline-none focus:ring-0 ${textareaSize}`}
	{name}
	{placeholder}
	{value}
	bind:this={textarea}
/>

// my-app/src/components/ui/autosized-textarea.tsx
"use client"

import React, { useEffect, useRef } from "react"
import autosize from "autosize"

import { cn } from "@/lib/utils"

interface AutosizedTextareaProps
  extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {}

export function AutosizedTextarea({
  name,
  placeholder,
  value,
  className,
  ...props
}: AutosizedTextareaProps) {
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  useEffect(() => {
    if (textareaRef.current) autosize(textareaRef.current)
  }, [])

  return (
    <textarea
      ref={textareaRef}
      className={cn(
        "h-14 w-full resize-none border-0 bg-transparent text-3xl font-bold focus:!outline-none focus:ring-0",
        className
      )}
      name={name}
      placeholder={placeholder}
      value={value}
      {...props}
    />
  )
}
