// src/components/Layout/DefaultHeader.svelte
<script lang="ts">
	import { openNavSidebar } from '$components/@ui/Drawer/drawer';

	import type { CurrentUser } from '$lib/types/user';
	import HamburgerIcon from '$components/@icons/HamburgerIcon.svelte';
	import SearchIcon from '$components/@icons/SearchIcon.svelte';
	import UserPopup from '$components/@ui/Popup/UserPopup.svelte';

	export let user: CurrentUser;
</script>

<header class="sticky top-0 z-40 w-full border-b bg-surface-50-900-token">
	<div class="container h-16 flex items-center justify-between">
		<div class="flex items-center gap-2">
			<button class="btn-icon md:hidden" on:click={() => openNavSidebar()}>
				<HamburgerIcon class="w-5 h-5" />
			</button>
			<!-- <MainNav /> -->
		</div>

		<div class="flex items-center gap-2">
			<a href="/search" class="btn-icon">
				<SearchIcon class="w-5 h-5" />
			</a>
			<UserPopup {user} />
		</div>
	</div>
</header>

// my-app/src/components/Layout/_DefaultHeader/DefaultHeader.tsx
import { Button } from "@/components/@ui/Button"
import { Icons } from "@/components/@ui/Icons"

import { HeaderLogo } from "./_HeaderLogo"
import { HeaderNav } from "./_HeaderNav"

const DefaultHeader = () => {
  return (
    <header className="sticky top-0 z-30 w-full border-b bg-background ">
      <div className="container flex h-16 items-center justify-between">
        <div className="flex items-center gap-4">
          <Button size="icon" className="md:hidden">
            <Icons.Hamburger className="h-5 w-5" />
          </Button>

          <div className="flex items-center gap-10">
            <HeaderLogo />
            <HeaderNav />
          </div>
        </div>
        <div></div>
      </div>
    </header>
  )
}

export { DefaultHeader }
