// real/src/routes/(base)/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';

	import programmingImage from '$lib/images/programming.svg';
	import { siteConfig } from '$lib/configs/site';

	import FireIcon from '$components/@icons/FireIcon.svelte';
	import ContrastIcon from '$components/@icons/ContrastIcon.svelte';
	import GenreIcon from '$components/@icons/GenreIcon.svelte';
	import ArrowRightIcon from '$components/@icons/ArrowRightIcon.svelte';
	import TextWithIcon from '$components/@ui/TextWithIcon.svelte';
	import TextSection from '$components/@ui/TextSection.svelte';
	import HomeHero from '$components/Hero/HomeHero/HomeHero.svelte';
	import ArticleGrid from '$components/Article/ArticleGrid.svelte';
	import ArticleItem from '$components/Article/ArticleItem/ArticleItem.svelte';
	import NoDataCard from '$components/@ui/NoDataCard.svelte';

	export let data: PageData;

	$: ({ topUsers, popularTags, trendingArticles } = data);
</script>

<div class="container py-12 md:py-20 space-y-40">
	<section>
		<HomeHero {topUsers} {popularTags} />
	</section>

	<section class="space-y-12">
		<TextSection
			title="Trending Articles"
			subTitle="요즘 뜨는 아티클들을 만나보세요"
			icon={FireIcon}
		/>

		{#if trendingArticles.length > 0}
			<ArticleGrid items={trendingArticles} let:item>
				<ArticleItem article={item} />
			</ArticleGrid>
		{:else}
			<NoDataCard text="아티클 데이터가 존재하지 않습니다!" />
		{/if}
	</section>

	<section>
		<TextSection
			title="더 많은 글들이 당신을 기다립니다"
			subTitle="지식과 영감을 얻고 유용하게 활용하세요"
			icon={ContrastIcon}
		/>

		<div class="grid grid-cols-1 gap-12 lg:grid-cols-2">
			<img src={programmingImage} class="max-w-[480px] lg:max-w-full mx-auto" alt="programming" />
			<div class="space-y-8">
				<div>
					<TextWithIcon
						icon={GenreIcon}
						size="3xl"
						class="!items-end"
						textClass="font-heading-token">Genre</TextWithIcon
					>
					<hr class="mt-3 mb-6 !border-surface-300" />
					<ul class="flex flex-wrap gap-3">
						{#each siteConfig.genre as genre (genre.title)}
							<li>
								<a href={genre.href} class="btn variant-filled text-sm">{genre.title}</a>
							</li>
						{/each}
					</ul>
				</div>

				<div class="flex flex-wrap gap-3">
					<a href="/articles" class="btn variant-filled-primary rounded-md">
						<span class="text-sm">아티클 보러가기</span>
						<span><ArrowRightIcon class="w-4 h-4" /></span>
					</a>

					<a href="/tags" class="btn variant-filled-secondary rounded-md">
						<span class="text-sm">태그 보러가기</span>
						<span><ArrowRightIcon class="w-4 h-4" /></span>
					</a>
				</div>
			</div>
		</div>
	</section>
</div>

// my-app/src/app/(base)/page.tsx
import Image from "next/image"
import Link from "next/link"

import { siteConfig } from "@/config/site"
import heroImageOne from "@/lib/images/hero-img-one.svg"
import { cn } from "@/lib/utils"
import { buttonVariants } from "@/components/ui/button"
import { Icons } from "@/components/ui/icons"
import { Separator } from "@/components/ui/seperator"
import { ArticleItem } from "@/components/Article/ArticleItem/ArticleItem"
import { HomeHero } from "@/components/Hero/HomeHero/HomeHero"

export default function IndexPage() {
  return (
    <>
      <section className="container py-16 md:py-20">
        <HomeHero />
      </section>

      <section className="container space-y-12 py-16 md:py-20">
        <div>
          <h3 className="font-heading text-4xl sm:text-5xl">
            Trending Articles
          </h3>
          <div className="flex items-center gap-1">
            <Icons.fire className="text-muted-foreground h-5 w-5" />
            <p className="text-muted-foreground text-lg font-thin">
              요즘 뜨는 아티클들을 만나보세요
            </p>
          </div>
        </div>

        <ul className="grid list-none grid-cols-1 gap-9 sm:grid-cols-2 lg:grid-cols-3">
          {Array.from({ length: 9 }).map((_, index) => (
            <li key={index}>
              <ArticleItem
                title={`타입스크립트에 대해 알아봅시다. 이것은 정말 중요합니다. - ${
                  index + 1
                }`}
                subTitle="Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit delectus voluptates sunt molestias aspernatur eveniet, pariatur quasi possimus hic aliquam ipsa nulla dicta eaque corrupti labore cumque qui, ipsam asperiores!"
                slug="/"
                coverImage={`https://picsum.photos/id/${
                  (index + 1) * 5
                }/600/450`}
                user={{
                  username: "커트니 러브",
                  avatar: "https://picsum.photos/id/237/128/128",
                  field: "Frontend",
                }}
                likeCount={245}
                commentCount={85}
                createdAt={new Date()}
                tags={[
                  "Serverside-Rendering",
                  "React",
                  "JavaScript",
                  "개발자",
                  "나의 이야기",
                ]}
              />
            </li>
          ))}
        </ul>
      </section>

      <section className="container space-y-4 py-16 md:py-20">
        <div>
          <h3 className="font-heading text-4xl sm:text-5xl">
            더 많은 글들이 당신을 기다립니다
          </h3>
          <div className="flex items-center gap-1">
            <Icons.carrot className="text-muted-foreground h-5 w-5" />
            <p className="text-muted-foreground text-lg font-thin">
              지식과 영감을 얻고 유용하게 활용하세요
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-12 lg:grid-cols-2">
          <Image src={heroImageOne} alt="hero-img-one" />
          <div className="space-y-8">
            <div>
              <div className="flex items-center gap-2">
                <Icons.boxes className="h-10 w-10" />
                <h3 className="font-heading text-3xl">Genre</h3>
              </div>
              <Separator className="my-4" />
              <ul className="flex flex-wrap gap-4">
                {siteConfig.genre.map((genre, index) => (
                  <li key={index} className="">
                    <Link
                      href={genre.href}
                      className={cn(
                        buttonVariants({ variant: "outline" }),
                        "hover:bg-foreground hover:text-background"
                      )}
                    >
                      {genre.title}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>

            <div className="flex flex-wrap gap-4">
              <Link
                href="/articles"
                className={buttonVariants({ variant: "default" })}
              >
                <Icons.ArrowRight className="mr-2" />
                <span className="text-base">아티클 페이지</span>
              </Link>

              <Link
                href="/tags"
                className={buttonVariants({ variant: "secondary" })}
              >
                <Icons.ArrowRight className="mr-2" />
                <span className="text-base">태그 페이지</span>
              </Link>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
