// my-app/src/app/(base)/auth/login/page.tsx
"use client"

import { Button } from "@/components/ui/button"
import { useToast } from "@/components/ui/use-toast"
import { FormInput } from "@/components/ui-blocks/FormInput"

export default function LoginPage() {
  const { toast } = useToast()

  return (
    <form>
      <div className="mb-8 flex flex-col gap-4">
        <FormInput
          type="text"
          name="username"
          labelText="아이디"
          placeholder="아이디를 입력하세요."
        />
        <FormInput
          type="password"
          name="password"
          labelText="비밀번호"
          placeholder="비밀번호를 입력하세요."
        />
      </div>

      <Button type="submit" className="w-full">
        로그인
      </Button>
    </form>
  )
}

// warmgun/src/routes/(app)/auth/login/+page.svelte
<script lang="ts">
	import FormInput from '$components/FormInput.svelte';
	import UserIcon from '~icons/ri/user-line';
	import PasswordIcon from '~icons/ri/lock-password-line';
</script>

<form>
	<div class="space-y-5 mb-8">
		<FormInput type="text" name="username" labelText="아이디" placeholder="아이디를 입력하세요.">
			<svelte:fragment slot="icon"><UserIcon /></svelte:fragment>
		</FormInput>
		<FormInput
			type="password"
			name="password"
			labelText="비밀번호"
			placeholder="비밀번호를 입력하세요."
		>
			<svelte:fragment slot="icon"><PasswordIcon /></svelte:fragment>
		</FormInput>
	</div>

	<button type="submit" class="w-full btn variant-filled-primary">로그인</button>
</form>
