// src/components/@item/Article/ArticleItem.svelte
<script lang="ts">
	import type { Article } from '$lib/types/article';
	import Image from '$components/@ui/Image.svelte';
	import ImageIcon from '$components/@icons/editor/ImageIcon.svelte';
	import TextWithIcon from '$components/@ui/TextWithIcon.svelte';
	import { categories } from '$lib/constants/categories';
	import { formatCount, formatDate } from '$lib/utils/format';
	import HeartIcon from '$components/@icons/HeartIcon.svelte';
	import CommentIcon from '$components/@icons/CommentIcon.svelte';

	export let article: Article;

	$: articleSlug = `/@${article.user.username}/${article.slug}`;
</script>

<div class="py-6 border-b border-b-surface-600">
	<header class="flex items-center justify-between gap-6">
		<div>
			<a href={articleSlug}>
				<h3 class="line-clamp-2 text-base sm:text-xl font-medium">{article.title}</h3>
			</a>

			<a href={articleSlug}>
				<p class="line-clamp-2 sm:line-clamp-3 text-sm sm:text-base font-light">
					{article.excerpt}
				</p>
			</a>
		</div>

		<div>
			<a href={articleSlug}>
				{#if article.coverImage}
					<div class="w-[80px] sm:w-[156px] h-full rounded-2xl shadow-xl overflow-hidden">
						<Image
							loading="lazy"
							src={`${article.coverImage}?w=400&h=300&q=80&f=webp`}
							alt="cover"
							class="aspect-[400/300] transition-all duration-500 ease-in-out hover:saturate-150 hover:scale-105"
							width={400}
							height={300}
						/>
					</div>
				{:else}
					<div
						class="flex w-[80px] sm:w-[156px] items-center justify-center aspect-[560/420] rounded-2xl shadow-xl bg-surface-700"
					>
						<ImageIcon class="w-10 h-10 sm:w-20 sm:h-20" />
					</div>
				{/if}
			</a>
		</div>
	</header>

	<footer class="flex items-center flex-wrap gap-2 mt-2">
		<ul class="flex gap-2">
			<li>
				<a class="badge variant-filled-primary" href="/article/${categories[article.category].slug}"
					>{categories[article.category].title}</a
				>
			</li>
			{#if article.tags.length > 0}
				<li>
					<a class="badge variant-filled xl:max-w-[110px]" href="/tag/{article.tags[0].slug}">
						<p class="text-ellipsis overflow-hidden">{article.tags[0].name}</p>
					</a>
				</li>
			{/if}
		</ul>

		<span class="opacity-75">·</span>

		<div class="flex items-center gap-2">
			<TextWithIcon
				icon={HeartIcon}
				size="sm"
				gap={1}
				iconClasses="text-red-500"
				textClasses="font-extralight text-sm">{formatCount(article._count.likes)}</TextWithIcon
			>
			<TextWithIcon icon={CommentIcon} size="sm" gap={1} textClasses="font-thin text-sm"
				>{formatCount(article._count.comments)}</TextWithIcon
			>
		</div>

		<span class="opacity-75">·</span>

		<span class="text-sm font-extralight">{formatDate(article.createdAt)}</span>
	</footer>
</div>

// src/components/article/article-item.tsx
import Image from "next/image"

import { formatDate } from "@/lib/format"
import { AspectRatio } from "@/components/@ui/aspect-ratio"

import { Avatar } from "../@ui/avatar"
import { Badge } from "../@ui/badge"
import { Card, CardBody, CardFooter, CardHeader } from "../@ui/card"
import { Icons } from "../@ui/icons"
import { Text } from "../@ui/text"
import { TextWithIcon } from "../@ui/text-with-icon"

type ArticleItemProps = {
  article: {
    title: string
    excerpt: string
    thumbnail: string
    user: {
      username: string
      avatar: string
    }
    tags: string[]
    createdAt: Date
  }
}

export const ArticleItem = ({ article }: ArticleItemProps) => {
  return (
    <div>
      <header className="flex items-center gap-2 pb-2">
        <Avatar src={article.user.avatar} size="sm" border={true} />
        <Text size="sm" weight={500}>
          {article.user.username}
        </Text>
        <span>·</span>
        <Text size="sm" color="light" weight={300}>
          {formatDate(article.createdAt)}
        </Text>
      </header>
      <Card className="space-y-2.5 overflow-hidden rounded-t-none">
        <div className="space-y-6">
          <AspectRatio ratio={16 / 10}>
            <Image
              src={article.thumbnail}
              alt="Photo by Drew Beamer"
              fill
              className="object-cover"
            />
          </AspectRatio>

          <div className="flex flex-col gap-1 px-6">
            <Text as="h3" size="md" weight={600} clamp={2}>
              {article.title}
            </Text>
            <Text as="p" weight={300} clamp={3} breaking="all">
              {article.excerpt}
            </Text>
          </div>
        </div>

        <footer className="flex items-center justify-between px-6 pb-6">
          <ul className="flex items-center gap-1.5">
            {article.tags.map((tag) => (
              <li key={tag}>
                <Badge variant="base-invert">{tag}</Badge>
              </li>
            ))}
          </ul>

          <div className="flex items-center gap-2">
            <TextWithIcon
              icon={<Icons.Heart className="h-4 w-4 text-red-500" />}
              text={<Text size="sm">12</Text>}
              gap={0.5}
            />
            <TextWithIcon
              icon={<Icons.Comment className="h-4 w-4" />}
              text={<Text size="sm">112</Text>}
              gap={0.5}
            />
          </div>
        </footer>
      </Card>
    </div>
  )
}
