// my-app/src/components/Article/ArticleItem/ArticleItem.tsx
import Image from "next/image"
import Link from "next/link"

import { formatDate } from "@/lib/utils"
import { buttonVariants } from "@/components/ui/button"
import { Icons } from "@/components/ui/icons"
import { UserAvatar } from "@/components/ui-blocks/UserAvatar"

interface ArticleItemProps {
  title: string
  subTitle: string
  slug: string
  coverImage: string | null
  likeCount: number
  commentCount: number
  createdAt: Date
  tags: string[]
  user: {
    username: string
    avatar: string | null
    field: string
  } | null
}

export function ArticleItem({
  title,
  subTitle,
  slug,
  coverImage,
  likeCount,
  commentCount,
  createdAt,
  tags,
  user,
}: ArticleItemProps) {
  return (
    <div className="flex flex-col gap-4">
      {user && (
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <UserAvatar src={user.avatar} avatarClassName="w-12 h-12" />
            <div className="flex flex-col">
              <span>{user.username}</span>
              <span className="text-muted-foreground font-extralight">
                {user.field}
              </span>
            </div>
          </div>
        </div>
      )}

      <Link href={slug}>
        <Image
          src={coverImage ? coverImage : ""}
          alt="cover"
          width={560}
          height={420}
          className="rounded-2xl shadow-xl"
        />
      </Link>
      <div className="flex flex-col gap-1">
        <Link href={slug}>
          <h3 className="line-clamp-2 text-xl">{title}</h3>
        </Link>
        <Link href={slug}>
          <p className="line-clamp-3 font-thin">{subTitle}</p>
        </Link>
      </div>

      <ul className="flex list-none flex-wrap gap-2">
        {tags.map((tag, index) => (
          <li key={index}>
            <Link
              href={`/tags/${tag}`}
              className={buttonVariants({ variant: "outline", size: "sm" })}
            >
              {tag}
            </Link>
          </li>
        ))}
      </ul>

      <div className="flex items-center justify-between">
        <div className="space-x-2">
          <span className="text-sm font-thin">On {formatDate(createdAt)}</span>
        </div>
        <div className="flex gap-2">
          <div className="flex items-center gap-1">
            <Icons.heart className="h-5 w-5 text-red-500" />
            <span className="text-sm font-thin">{likeCount}</span>
          </div>
          <div>
            <div className="flex items-center gap-1">
              <Icons.chat className="h-5 w-5" />
              <span className="text-sm font-thin">{commentCount}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// real/src/lib/components/Article/ArticleItem/ArticleItem.svelte
<script lang="ts">
	import type { Article } from '$lib/types/article';

	import { formatDate } from '$lib/utils/format';
	import UserAvatar from '$lib/components/@ui/UserAvatar.svelte';
	import HeartIcon from '$lib/components/@icons/HeartIcon.svelte';
	import CommentIcon from '$lib/components/@icons/CommentIcon.svelte';

	export let article: Article;

	$: articleSlug = `/@${article.author.username}/${article.slug}`;
</script>

<div class="flex flex-col gap-4">
	<div class="flex items-center justify-between">
		<div class="flex items-center gap-2">
			<UserAvatar src={article.author.profile?.avatar} width="w-12" />
			<div class="flex flex-col">
				<span>{article.author.profile?.nickname}</span>
				<span class="text-muted-foreground font-extralight">
					{article.author.profile?.field}
				</span>
			</div>
		</div>
	</div>

	<a href={articleSlug}>
		<img
			src={article.coverImage ? `${article.coverImage}?w=560&h=420&q=80&f=webp` : ''}
			alt="cover"
			class="aspect-[560/420] rounded-2xl shadow-xl"
		/>
	</a>
	<div class="flex flex-col gap-1">
		<a href={articleSlug}>
			<h3 class="line-clamp-2 text-xl">{article.title}</h3>
		</a>
		<a href={articleSlug}>
			<p class="line-clamp-3 font-thin">{article.excerpt}</p>
		</a>
	</div>

	<ul class="flex list-none flex-wrap gap-2">
		{#each article.tags as tag (tag.id)}
			<li>
				<a href={`/tags/${tag.name}`}>
					{tag.name}
				</a>
			</li>
		{/each}
	</ul>

	<div class="flex items-center justify-between">
		<div class="space-x-2">
			<span class="text-sm font-thin">On {formatDate(article.createdAt)}</span>
		</div>
		<div class="flex gap-2">
			<div class="flex items-center gap-1">
				<HeartIcon class="h-5 w-5 text-red-500" />
				<span class="text-sm font-thin">{article._count.likes}</span>
			</div>
			<div>
				<div class="flex items-center gap-1">
					<CommentIcon class="h-5 w-5" />
					<span class="text-sm font-thin">{article._count.comments}</span>
				</div>
			</div>
		</div>
	</div>
</div>
