// my-app/src/components/Header/SiteHeader/MainNav/MainNav.tsx
import * as React from "react"
import Link from "next/link"

import { siteConfig } from "@/lib/site"
import { LogoIcon } from "@/components/@icons/LogoIcon"

export function MainNav() {
  return (
    <nav className="flex items-center gap-10">
      <Link href="/" className="flex items-center gap-2">
        <LogoIcon className="h-6 w-6" />
        <h2 className="hidden font-bold md:block">{siteConfig.name}</h2>
      </Link>

      <ul className="hidden md:flex md:gap-6">
        {siteConfig.mainNav.map((item, index) => (
          <li key={index}>
            <Link
              href={item.href}
              className="text-muted-foreground flex items-center text-sm font-semibold"
            >
              {item.title}
            </Link>
          </li>
        ))}
      </ul>
    </nav>
  )
}

// real/src/lib/components/Header/AppHeader/MainNav/MainNav.svelte
<script lang="ts">
	import { siteConfig } from '$lib/configs/site';

	import LogoIcon from '$lib/components/@icons/LogoIcon.svelte';
</script>

<nav class="flex items-center gap-10">
	<div class="flex items-center gap-2">
		<LogoIcon class="h-6 w-6" />
		<h2 class="hidden font-bold md:block">{siteConfig.name}</h2>
	</div>

	<ul class="hidden md:flex md:gap-6">
		{#each siteConfig.mainNav.slice(1, siteConfig.mainNav.length) as link (link.href)}
			<li class="text-sm font-semibold opacity-75">
				<a href={link.href}>{link.title}</a>
			</li>
		{/each}
	</ul>
</nav>
