// src/components/Home/HomeHero/HomeHero.svelte
<script lang="ts">
	import type { Article } from '$lib/types/article';

	import MainWords from './_MainWords.svelte';
	import SubWords from './_SubWords.svelte';
	import HeroGradient from './_HeroGradient.svelte';
	import ArticleShowcase from './_ArticleShowcase.svelte';
	import NoDataCard from '$components/@ui/NoDataCard.svelte';

	export let articles: Article[];
</script>

<div class="grid grid-cols-1 gap-8 items-center md:gap-10 lg:grid-cols-2">
	<div class="relative z-20 space-y-4 mx-auto md:space-y-6 lg:mx-0">
		<MainWords />
		<SubWords />
	</div>

	<div class="relative w-full h-full mx-auto">
		<HeroGradient />
		{#if articles.length > 0}
			<ArticleShowcase {articles} />
		{:else}
			<NoDataCard />
		{/if}
	</div>
</div>

// src/app/_components/home-hero.tsx
import { fetchPickedArticles } from "@/lib/services/article/fetch"

import { ArticleShowcase } from "./article-showcase"
import { SiteWords } from "./site-words"

export const HomeHero = async () => {
  const pickedArticles = await fetchPickedArticles()

  return (
    <div className="grid grid-cols-1 items-center gap-8 md:gap-10 lg:grid-cols-2">
      <SiteWords />
      <ArticleShowcase articles={pickedArticles} />
    </div>
  )
}
