// my-app/src/components/Header/WriteHeader/WriteHeader.tsx
import { Button } from "@/components/ui/button"
import { Icons } from "@/components/ui/icons"

export function WriteHeader() {
  return (
    <header className="flex items-center justify-between px-2 py-4 sm:px-6">
      <div className="flex items-center gap-2">
        <Button variant="ghost" className="h-12 w-12 p-0">
          <Icons.arrowLeft className="h-6 w-6" />
        </Button>
        <Button variant="outline" className="h-12 w-12 border-2 p-0">
          <Icons.article className="h-6 w-6" />
        </Button>
      </div>

      <div className="flex items-center gap-2">
        <Button variant="secondary" size="lg">
          저장
        </Button>
        <Button variant="default" size="lg">
          글 등록
        </Button>
      </div>
    </header>
  )
}

// src/routes/write/_WriteHeader/WriteHeader.svelte
<script lang="ts">
	import { base } from '$app/paths';
	import { afterNavigate } from '$app/navigation';
	import { drawerStore } from '@skeletonlabs/skeleton';

	let previousPage: string = base;

	function openWriterSidebar() {
		drawerStore.open();
	}

	afterNavigate(({ from }) => {
		previousPage = from?.url.pathname || previousPage;
	});
</script>

<header class="flex justify-between p-5">
	<div>
		<a href={previousPage} class="btn-icon"><i class="ri-arrow-left-line ri-lg" /></a>
		<button class="btn-icon variant-ghost-surface" on:click={openWriterSidebar}
			><i class="ri-article-line ri-lg" /></button
		>
	</div>

	<div class="flex gap-4">
		<button class="btn variant-filled-secondary btn-base">저장</button>
		<button class="btn variant-filled-primary btn-base">글 등록</button>
	</div>
</header>
