// src/components/editor/editor.tsx
"use client"

import "highlight.js/styles/stackoverflow-dark.css"

import React from "react"
import CodeBlockLowlight from "@tiptap/extension-code-block-lowlight"
import Image from "@tiptap/extension-image"
import Link from "@tiptap/extension-link"
import Underline from "@tiptap/extension-underline"
import { EditorContent, EditorOptions, useEditor } from "@tiptap/react"
import StarterKit from "@tiptap/starter-kit"
import { common, createLowlight } from "lowlight"

import { BubbleMenu } from "./bubble-menu"
import { FloatingMenu } from "./floating-menu"

type EditorProps = {
  body?: unknown
} & Partial<Pick<EditorOptions, "onCreate" | "onUpdate" | "editable">>

export const Editor = ({ body, ...props }: EditorProps) => {
  const editor = useEditor({
    content: body ?? ``,
    extensions: [
      StarterKit.configure({
        codeBlock: false,
        heading: {
          levels: [1, 2, 3],
        },
      }),
      Underline,
      Link,
      CodeBlockLowlight.configure({
        lowlight: createLowlight(common),
        HTMLAttributes: {
          class: "hljs",
        },
      }),
      Image.configure({
        HTMLAttributes: {
          class: "mx-auto",
        },
      }),
    ],
    editorProps: {
      attributes: {
        class:
          "prose prose-a:cursor-pointer prose-a:no-underline prose-a:text-blue-600 hover:prose-a:underline dark:prose-invert focus:outline-none",
      },
    },
    autofocus: true,
    ...props,
  })

  if (!editor) {
    return null
  }

  return (
    <>
      <EditorContent editor={editor} />
      <BubbleMenu editor={editor} />
      <FloatingMenu editor={editor} />
    </>
  )
}

// src/components/Write/Editor/Editor.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import type { Readable } from 'svelte/store';

	import { lowlight } from 'lowlight';
	import html from 'highlight.js/lib/languages/xml';
	import css from 'highlight.js/lib/languages/css';
	import js from 'highlight.js/lib/languages/javascript';
	import ts from 'highlight.js/lib/languages/typescript';

	import {
		createEditor,
		Editor,
		Document,
		Text,
		Paragraph,
		Heading,
		ListItem,
		BulletList,
		OrderedList,
		Blockquote,
		CodeBlockLowlight,
		Image,
		Bold,
		Italic,
		Strike,
		InlineCode,
		TextStyle,
		Underline,
		Link,
		History
	} from './Editor';

	import EditorContent from './_EditorContent.svelte';
	import BubbleMenu from './_BubbleMenu.svelte';

	lowlight.registerLanguage('html', html);
	lowlight.registerLanguage('css', css);
	lowlight.registerLanguage('js', js);
	lowlight.registerLanguage('ts', ts);

	let editor: Readable<Editor>;

	onMount(() => {
		editor = createEditor({
			extensions: [
				Document,
				Text,
				Paragraph,
				Heading.configure({ levels: [1, 2, 3] }),
				ListItem,
				BulletList,
				OrderedList,
				Blockquote,
				CodeBlockLowlight.configure({
					lowlight
				}),
				Image,
				Bold,
				Italic,
				Strike,
				InlineCode,
				TextStyle,
				Underline,
				Link,
				History
			],
			editorProps: {
				attributes: {
					class: 'prose dark:prose-invert p-4 focus:outline-none'
				}
			},
			autofocus: true,
			editable: true,
			content: `Hello world!`
		});
	});
</script>

<EditorContent editor={$editor} />
{#if $editor}
	<BubbleMenu editor={$editor}>
		<button on:click={() => $editor.chain().focus().toggleBold().run()}> 굵게 </button>
		<button on:click={() => $editor.chain().focus().toggleItalic().run()}> 기울임 </button>
		<button on:click={() => $editor.chain().focus().toggleStrike().run()}> 취소선 </button>
		<button on:click={() => $editor.chain().focus().toggleCode().run()}> 인라인 코드 </button>
	</BubbleMenu>
{/if}
