// real/src/routes/(base)/(sub)/auth/signup/+page.svelte
<script lang="ts">
	import type { ActionData } from './$types';
	import { enhance } from '$app/forms';

	import { triggerToast } from '$components/@ui/Toast/toast';
	import UserIcon from '$components/@icons/UserIcon.svelte';
	import PasswordIcon from '$components/@icons/PasswordIcon.svelte';
	import CheckIcon from '$components/@icons/CheckIcon.svelte';
	import EmailIcon from '$components/@icons/EmailIcon.svelte';
	import FormInput from '$components/@ui/FormInput.svelte';

	export let form: ActionData;

	$: if (form?.message) {
		triggerToast('warning', form.message);
	}
</script>

<form method="POST" use:enhance>
	<div class="space-y-5 mb-8">
		<FormInput
			type="text"
			name="username"
			labelText="아이디"
			helperText="* 5~20자 사이의 영문 소문자/숫자 입력"
			placeholder="아이디를 입력하세요."
			icon={UserIcon}
		/>
		<FormInput
			type="password"
			name="password"
			labelText="비밀번호"
			helperText="* 8~20자 사이, 영문/숫자/특수 문자 중 2가지 이상 포함"
			placeholder="비밀번호를 입력하세요."
			icon={PasswordIcon}
		/>
		<FormInput
			type="password"
			name="confirm"
			labelText="비밀번호 확인"
			placeholder="앞선 비밀번호와 동일하게 작성하세요."
			icon={CheckIcon}
		/>
		<FormInput
			type="email"
			name="email"
			labelText="이메일"
			placeholder="이메일을 입력하세요."
			icon={EmailIcon}
		/>
	</div>

	<button type="submit" class="w-full btn variant-filled-primary">회원가입</button>
</form>

// my-app/src/app/(base)/auth/signup/page.tsx
"use client"

import { revalidateTag } from "next/cache"
import { redirect } from "next/navigation"

import { Button } from "@/components/ui/button"
import { useToast } from "@/components/ui/use-toast"
import { FormInput } from "@/components/ui-blocks/FormInput"

export default function Signupage() {
  const { toast } = useToast()

  return (
    <form>
      <div className="mb-8 flex flex-col gap-4">
        <FormInput
          type="text"
          name="username"
          labelText="아이디"
          helperText="* 5~20자 사이의 영문 소문자/숫자 입력"
          placeholder="아이디를 입력하세요."
        />
        <FormInput
          type="password"
          name="password"
          labelText="비밀번호"
          helperText="* 8~20자 사이, 영문/숫자/특수 문자 중 2가지 이상 포함"
          placeholder="비밀번호를 입력하세요."
        />
        <FormInput
          type="password"
          name="confirm"
          labelText="비밀번호 확인"
          placeholder="앞선 비밀번호와 동일하게 작성하세요."
        />
        <FormInput
          type="email"
          name="email"
          labelText="이메일"
          placeholder="이메일을 입력하세요."
        />
      </div>

      <Button type="submit" className="w-full">
        회원가입
      </Button>
    </form>
  )
}
