// my-app/src/components/Hero/HomeHero/TopBlogerCard/TopBlogerCard.tsx
import React from "react"
import Link from "next/link"

import { Icons } from "@/components/ui/icons"
import { UserAvatar } from "@/components/ui-blocks/UserAvatar"

interface TopBlogerCardProps {
  username: string
  avatar: string | null
  field: string
  bio: string
  followedByCount: number
  followingCount: number
  articleCount: number
}

export function TopBlogerCard({
  username,
  avatar,
  field,
  bio,
  followedByCount,
  followingCount,
  articleCount,
  ...props
}: TopBlogerCardProps) {
  return (
    <div
      className="grid h-full min-h-[300px] w-full overflow-hidden rounded-lg shadow-xl"
      {...props}
    >
      <header className="grid grid-cols-3 items-center gap-8 bg-neutral-100 p-4 text-neutral-800">
        <div className="flex items-center justify-center">
          <UserAvatar
            src={avatar}
            alt={`${username}-avatar`}
            avatarClassName="w-14 h-14 min-[500px]:w-full min-[500px]:h-full min-[500px]:aspect-square min-[500px]:rounded-md"
            fallbackClassName="rounded-md"
          />
        </div>
        <div className="col-span-2 space-y-2">
          <UserProfile username={username} field={field} bio={bio} />
        </div>
      </header>

      <footer className="flex items-center justify-between bg-white p-6 text-neutral-800 sm:p-10">
        <div className="flex items-center gap-6 md:gap-10">
          <UserStatus title="구독자" count={followedByCount} />
          <UserStatus title="팔로잉" count={followingCount} />
          <UserStatus title="아티클" count={articleCount} />
        </div>
        <Link
          href={`/@${username}`}
          className="bg-background text-foreground hover:text-background rounded-full 
          border p-2 shadow-lg transition-colors duration-150 hover:border-neutral-500 hover:bg-white"
        >
          <Icons.arrowRightIn className="h-6 w-6" />
        </Link>
      </footer>
    </div>
  )
}

interface UserProfileProps {
  field: string
  username: string
  bio: string
}

function UserProfile({ field, username, bio }: UserProfileProps) {
  return (
    <>
      <span className="line-clamp-1 opacity-50 sm:text-lg">{field}</span>
      <span className="line-clamp-1 text-lg sm:text-2xl">{username}</span>
      <p className="line-clamp-2 break-all font-light sm:text-lg">{bio}</p>
    </>
  )
}

interface UserStatusProps {
  title: string
  count: number
}

function UserStatus({ title, count }: UserStatusProps) {
  return (
    <div className="flex flex-col">
      <span className="text-xs font-semibold sm:text-sm">{title}</span>
      <span className="text-sm font-light">{count}</span>
    </div>
  )
}

// real/src/components/Hero/HomeHero/_TopBlogerCard/TopBlogerCard.svelte
<script lang="ts">
	import UserAvatar from '$components/@ui/UserAvatar.svelte';
	import ArrowRightTwoIcon from '$components/@icons/ArrowRightTwoIcon.svelte';

	export let username: string;
	export let avatar: string | null | undefined;
	export let bio: string | undefined;
	export let field: string | undefined;
	export let followedByCount: number;
	export let followingCount: number;
	export let articleCount: number;
</script>

<div class="shadow-xl">
	<header class="grid grid-cols-3 gap-8 items-center p-4 bg-neutral-100 text-neutral-800">
		<UserAvatar src={avatar} width="w-full" rounded="rounded-lg" />
		<div class="col-span-2 space-y-2">
			<span class="opacity-50 line-clamp-1 sm:text-lg">{field}</span>
			<span class="font-serif font-semibold line-clamp-1 text-lg sm:text-2xl">{username}</span>
			<p class="font-light line-clamp-2 break-all sm:text-lg">{bio}</p>
		</div>
	</header>

	<footer class="flex justify-between items-center p-8 sm:p-10 bg-white text-neutral-800">
		<div class="grid grid-cols-3">
			<div class="flex flex-col">
				<span class="font-semibold text-xs sm:text-sm">구독자</span>
				<span class="font-light text-sm">{followedByCount}</span>
			</div>
			<div class="flex flex-col">
				<span class="font-semibold text-xs sm:text-sm">팔로잉</span>
				<span class="font-light text-sm">{followingCount}</span>
			</div>
			<div class="flex flex-col">
				<span class="font-semibold text-xs sm:text-sm">작성한 아티클</span>
				<span class="font-light text-sm">{articleCount}</span>
			</div>
		</div>

		<div>
			<a
				href={`/@${username}`}
				class="btn-icon bg-surface-900 shadow-lg text-surface-50 hover:bg-surface-50 hover:text-surface-900 hover:border hover:border-surface-300"
			>
				<ArrowRightTwoIcon />
			</a>
		</div>
	</footer>
</div>
