// src/components/shell/default-header.tsx
import Link from "next/link"

import { buttonVariants } from "@/components/@ui/button"
import { Container } from "@/components/@ui/container"

import { HeaderLogo } from "./header-logo"
import { MainNav } from "./main-nav"

const DefaultHeader = () => {
  return (
    <header className="sticky top-0 z-30 w-full border-b bg-background">
      <Container
        variant="wide"
        center={true}
        className="flex h-16 items-center justify-between"
      >
        <section className="flex items-center gap-10">
          <div className="space-x-2">
            {/* TODO: HambergurSheet */}
            <HeaderLogo />
          </div>
          <MainNav />
        </section>
        <section>
          <Link
            href="/login"
            className={buttonVariants({ variant: "default" })}
          >
            로그인
          </Link>
        </section>
      </Container>
    </header>
  )
}

export { DefaultHeader }

// src/components/Layout/DefaultHeader/DefaultHeader.svelte
<script lang="ts">
	import HamburgerButton from './_HamburgerButton.svelte';
	import MainNav from './_MainNav.svelte';
	import SearchLink from './_SearchLink.svelte';
	import UserPopup from '$components/Auth/UserPopup.svelte';
</script>

<header class="sticky top-0 z-30 w-full border-b bg-surface-50-900-token border-b-surface-600">
	<div class="container h-16 flex items-center justify-between">
		<div class="flex items-center gap-2">
			<HamburgerButton />
			<MainNav />
		</div>

		<div class="flex items-center gap-2">
			<SearchLink />
			<UserPopup />
		</div>
	</div>
</header>
