// my-app/src/components/main-nav.tsx
import * as React from "react"
import Link from "next/link"

import { NavItem } from "@/types/nav"
import { siteConfig } from "@/config/site"
import { cn } from "@/lib/utils"
import { Icons } from "@/components/ui/icons"

interface MainNavProps {
  items?: NavItem[]
}

export function MainNav({ items }: MainNavProps) {
  return (
    <div className="flex gap-6 md:gap-10">
      <Link href="/" className="hidden items-center space-x-2 md:flex">
        <Icons.logo className="h-6 w-6" />
        <span className="hidden font-bold sm:inline-block">
          {siteConfig.name}
        </span>
      </Link>
      {items?.length ? (
        <nav className="hidden gap-6 md:flex">
          {items?.map(
            (item, index) =>
              item.href && (
                <Link
                  key={index}
                  href={item.href}
                  className={cn(
                    "text-muted-foreground flex items-center text-lg font-semibold sm:text-sm",
                    item.disabled && "cursor-not-allowed opacity-80"
                  )}
                >
                  {item.title}
                </Link>
              )
          )}
        </nav>
      ) : null}
    </div>
  )
}

// real/src/components/Header/AppHeader/MainNav/MainNav.svelte
<script lang="ts">
	import { siteConfig } from '$lib/configs/site';

	import LogoIcon from '$components/@icons/LogoIcon.svelte';
</script>

<nav class="flex items-center gap-10">
	<a href="/" class="flex items-center gap-2">
		<LogoIcon class="h-6 w-6" />
		<h2 class="hidden font-bold md:block">{siteConfig.name}</h2>
	</a>

	<ul class="hidden md:flex md:gap-6">
		{#each siteConfig.mainNav.slice(1, siteConfig.mainNav.length) as link (link.href)}
			<li class="text-sm font-semibold opacity-75">
				<a href={link.href}>{link.title}</a>
			</li>
		{/each}
	</ul>
</nav>
