// src/components/Home/HomeHero/HomeHero.svelte
<script lang="ts">
	import MainWords from './_MainWords.svelte';
	import SubWords from './_SubWords.svelte';
	import HeroGradient from './_HeroGradient.svelte';
	import ArticleShowcase from './_ArticleShowcase.svelte';

	const articles = Array.from({ length: 10 }, (v, i) => ({
		id: i + 1,
		title: `스벨트킷은 훌륭합니다! ${i + 1}`,
		coverImage: `https://picsum.photos/id/${(i + 1) * 7}/360/580`,
		user: {
			profile: {
				nickname: 'Shadcn',
				avatar: 'https://github.com/shadcn.png'
			}
		},
		tags: ['JavaScript', 'TypeScript', '개발 이야기'],
		category: 'FRONTEND'
	}));
</script>

<div class="grid grid-cols-1 gap-8 items-center md:gap-10 lg:grid-cols-2">
	<div class="relative z-20 space-y-4 mx-auto md:space-y-6 lg:mx-0">
		<MainWords />
		<SubWords />
	</div>

	<div class="relative w-full h-full max-w-[640px] mx-auto">
		<HeroGradient />
		<ArticleShowcase {articles} />
	</div>
</div>

// src/components/home/home-hero/index.tsx
import { ArticleShowcase } from "./article-showcase"
import { HeroGradient } from "./hero-gradient"
import { HeroMainWords } from "./hero-main-words"
import { HeroSubWords } from "./hero-sub-words"

const articles = Array.from({ length: 10 }, (_, i) => {
  return {
    id: i + 1,
    title: `테스트용 아티클입니다. 굉장히 재미있는 개발이군요.. - ${i + 1}`,
    excerpt:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum modi pariatur alias. Natus animi in officiis nesciunt laborum reiciendis est voluptatibus nihil sunt! Sit optio inventore laudantium eveniet aperiam non.",
    thumbnail: `https://picsum.photos/id/${(i + 1) * 27}/${270 * 2}/${405 * 2}`,
    user: {
      nickname: `테스트용 계정 ${i + 1}`,
      avatar: "https://i.pravatar.cc/300",
    },
    category: "프론트엔드",
    tags: ["Svelte", "Typescript"],
  }
})

const HomeHero = () => {
  return (
    <div className="grid grid-cols-1 items-center gap-8 md:gap-10 lg:grid-cols-2">
      <div className="relative z-20 mx-auto space-y-4 md:space-y-6 lg:mx-0">
        <HeroMainWords />
        <HeroSubWords />
      </div>

      <div className="relative mx-auto h-full w-full">
        <HeroGradient />
        <ArticleShowcase articles={articles} />
      </div>
    </div>
  )
}

export { HomeHero }
